services:
  db:
    image: "postgres:14-alpine"
    env_file: .env.development
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - "./backups:/var/lib/postgresql/backups"
  web:
    build: .
    env_file: .env.development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: "rails s -b 0.0.0.0"
    depends_on:
      - db
volumes:
  postgres: